name: Publish GitHub release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish release to GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
#          cache: true
#          cache-dependency-path: FlexPkg/packages.lock.json
        
      - name: Build for Windows (x64)
        run: dotnet publish -c Release -r win-x64 FlexPkg
        
      - name: Zip Windows (x64) build
        run: |
          cd FlexPkg/bin/Release/net8.0/win-x64/publish
          zip -r FlexPkg-windows-x64.zip .
          
      - name: Build for Linux (x64)
        run: dotnet publish -c Release -r linux-x64 FlexPkg

      - name: Zip Linux (x64) build
        run: |
          cd FlexPkg/bin/Release/net8.0/linux-x64/publish
          zip -r FlexPkg-linux-x64.zip .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: FlexPkg/bin/Release/net8.0/**/publish/FlexPkg-*.zip