name: Publish GitHub release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish release to GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: FlexPkg/packages.lock.json

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release FlexPkg
        
      - name: ZIP the build
        run: |
          cd ./FlexPkg/bin/release/net8.0/publish
          zip -r FlexPkg.zip .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: FlexPkg.zip